<a href="https://colab.research.google.com/github/shikhaguptadr/Natural-Language-Processing/blob/main/Spam_Mail_Prediction(Logistic_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Spam Mail Prediction

**Import Dependancy**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix

**Import the mail data**

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Toppers Acadmy Data/data/Machine Learning/Chapter 5:- Natural language processing(NLP)/Project/Copy of mail_data.csv')

In [ ]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.shape

(5572, 2)

In [ ]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [ ]:
df['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

### Lable Encoding

*   ham	converted as 1
*   spam converted as 0



In [ ]:
df['label'] = df['Category'].map({'spam':1,'ham':0})

### Train Test Split

**Sepret data as x and y**

In [ ]:
x = df['Message']
y = df['label']

In [ ]:
x.head()

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: Message, dtype: object

In [ ]:
y.head()

0    0
1    0
2    1
3    0
4    0
Name: label, dtype: int64

**Spliting the data as train data and test data**

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train

1978    Reply to win £100 weekly! Where will the 2006 ...
3989    Hello. Sort of out in town already. That . So ...
3935     How come guoyang go n tell her? Then u told her?
4078    Hey sathya till now we dint meet not even a si...
4086    Orange brings you ringtones from all time Char...
                              ...                        
3772    Hi, wlcome back, did wonder if you got eaten b...
5191                               Sorry, I'll call later
5226        Prabha..i'm soryda..realy..frm heart i'm sory
5390                           Nt joking seriously i told
860               Did he just say somebody is named tampa
Name: Message, Length: 4457, dtype: object

### Feature Extraction

**convert text data into numerical data**

In [ ]:
vector = TfidfVectorizer(min_df=1, stop_words='english', lowercase=True)
x_train = vector.fit_transform(x_train)
x_test = vector.transform(x_test)

In [ ]:
print(x_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34840 stored elements and shape (4457, 7440)>
  Coords	Values
  (0, 5512)	0.1898892037332199
  (0, 7222)	0.2173884735352799
  (0, 258)	0.2379428657041507
  (0, 7162)	0.2550284465664535
  (0, 354)	0.3544175987866074
  (0, 2724)	0.3544175987866074
  (0, 7300)	0.24288153842988894
  (0, 2049)	0.3034375179183143
  (0, 3262)	0.33791755486732394
  (0, 5800)	0.17558937755823417
  (0, 6264)	0.1898892037332199
  (0, 694)	0.3171299579602537
  (0, 2497)	0.2442158912653505
  (0, 5818)	0.22682143517864364
  (1, 3267)	0.26787130770292167
  (1, 6109)	0.32397626344658004
  (1, 6738)	0.28986069568917994
  (1, 2335)	0.21623212751660786
  (1, 5650)	0.3604441444703179
  (1, 3333)	0.20665394084233094
  (1, 2440)	0.3387054464839871
  (1, 4509)	0.40282459910606705
  (1, 3932)	0.24325511357721422
  (1, 3804)	0.19029023465152678
  (1, 2555)	0.3840709491751003
  :	:
  (4452, 3084)	0.22948428918295163
  (4452, 3290)	0.26370969643076225
  (4452, 3978)	0

In [ ]:
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [ ]:
train_pred[:5]

array([1, 0, 0, 0, 1])

In [ ]:
y_train.head()

1978    1
3989    0
3935    0
4078    0
4086    1
Name: label, dtype: int64

In [ ]:
test_pred[:5]

array([0, 0, 0, 0, 0])

In [ ]:
y_test.head()

3245    0
944     0
1044    0
2484    0
812     0
Name: label, dtype: int64

In [ ]:
print('Train dataset acc :- ',accuracy_score(y_train,train_pred))
print('Train dataset confusion matrix :- \n',confusion_matrix(y_train,train_pred))

Train dataset acc :-  0.9670181736594121
Train dataset confusion matrix :- 
 [[3855    4]
 [ 143  455]]


In [ ]:
print('Test dataset acc :- ',accuracy_score(y_test,test_pred))
print('Test dataset confusion matrix :- \n',confusion_matrix(y_test,test_pred))

Test dataset acc :-  0.967713004484305
Test dataset confusion matrix :- 
 [[966   0]
 [ 36 113]]


### Building a Predictive System

In [ ]:
sms = ['i am going to delhi']
data = vector.transform(sms)
pred = model.predict(data)
if pred[0] == 1:
  print('Spam')
else:
  print('Ham')

Ham


In [ ]:
y.head(1)

0    0
Name: label, dtype: int64

In [ ]:
x[0][0:]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [ ]:
sms = ['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...']
data = vector.transform(sms)
pred = model.predict(data)
if pred[0] == 1:
  print('Spam')
else:
  print('Ham')

Ham
